### ISSUE TITLE
flag 'flagfile' was defined more than once

### ISSUE THREAD

**Issue by zoooo0820** [baidu/Familia#10]
如果不export第三方库的话会出现动态库错误，但是引入第三方库后就遇到这个问题
ERROR: flag 'flagfile' was defined more than once (in files 'src/gflag.cc' and '    ') 分别是绝对路径和相对路径

**Comment by ZeyuChen** [comment]
请问你的运行环境是Linux还是Mac？ sh build.sh 之后可以运行demo的脚本吗？

**Comment by zoooo0820** [comment]
环境是linux，build后可以执行下载demo的脚本，但是后面的执行脚本不能运行，错误就跟之前描述过的一样

**Comment by zoooo0820** [comment]
您好，我去掉了makefile中 -lgflag的编译选项，现在可以正常运行了。
推测是之前安装caffe的时候有gflag导致的重复问题

**Comment by ZeyuChen** [comment]
好的，如果编译和运行没问题就close issues了。
