### ISSUE TITLE
Does Familia support the training of topic models?

### ISSUE THREAD

**Issue by jonaschn** [baidu/Familia#111]
I don't speak Chinese and it's hard to figure out what the purpose of this project is.
Does Familia support the training of different topic models(sentenceLDA, LDA or TWE) on custom datasets?
Or is it inference of unseen data using pre-trained models (download_models.sh) only?

**Comment by DesmonDay** [comment]
Yes, it is only the inference using pre-trained models.

**Comment by jonaschn** [comment]
Thanks for your fast reply. Is it planned to release the code for training the models?

**Comment by DesmonDay** [comment]
We don't have this plan for the moment, sorry.
