### ISSUE TITLE
TWE的具体实现以及模型展示结果中的计算方式

### ISSUE THREAD

**Issue by judaschrist** [baidu/Familia#13]
TWE的原论文中实际上有三种实现方式，请问这个包里具体实现了哪一种呢？
另外，TWE的模型展示中展示了两列结果。其中多项分布结果直接由LDA得到，而每个主题embedding结果是如何计算的呢？根据论文，TWE中的embedding是直接利用了每个词的主题分配，似乎并不影响原来的LDA结果，能否进一步说明？

**Comment by lianrzh** [comment]
1.关于TWE的三种实现方式，Familia提供的是第一种，即TWE-1。
2.每个主题的embedding结果是根据主题对应的embedding去跟词表中的词计算cosine距离并返回最相关的k个词，这个在代码中有所体现。
3.TWE中是先训练LDA，再进行embedding的训练，所以并不会影响原来的LDA结果。
