### ISSUE TITLE
词表文件vocab_info.txt 中 后面两列表示的含义是什么？

### ISSUE THREAD

**Issue by lrjocean** [baidu/Familia#15]
word    中国    0       64993051.0      14733379.0
word    公司    1       63616379.0      10172354.0
word    发展    2       47508805.0      12369856.0
word    市场    3       46457573.0      10721555.0
word    工作    4       44673705.0      13794068.0
word    企业    5       41719656.0      9119845.0
word    记者    6       33865364.0      16632006.0
word    服务    7       29299537.0      8780211.0
word    经济    8       28382905.0      8445786.0

**Comment by lianrzh** [comment]
最后两列分别表示该词在语料中的TF(term frequency)跟DF(document frequency)

**Comment by lianrzh** [comment]
@mjc14 是按照分词后统计出来的。
