### ISSUE TITLE
希望python接口提供更多底层接口实现

### ISSUE THREAD

**Issue by FelixHo** [baidu/Familia#19]
想通过TWE实现类似'关键词提取'、'词与词之间的相似度'等方面的需求，但目前提供的python接口貌似还没法获取到模型的底层数据，例如：词向量（word_emb）、主题向量（topic_emb）等

**Comment by lianrzh** [comment]
由于模型中保存了词向量和向量的信息，可以参考`semantic_matching.cpp`中的`load_emb()`函数对二进制模型进行解析，后续会提供更多底层接口。
