### ISSUE TITLE
请问下我怎么通过TWE从一篇文章提取关键词呢？

### ISSUE THREAD

**Issue by vega110** [baidu/Familia#25]
是否存在接口可以从一篇文章中提取关键词？

**Comment by lianrzh** [comment]
没有直接的接口提供做关键词抽取，LDA或TWE计算出来的相似度一般是作为一个特征加入到抽关键词算法中，单独使用效果不是很理想。

**Comment by lianrzh** [comment]
@vega110 关键词抽取属于"短文本-长文本"应用范式的一种，在`document_keywords_demo`中示例使用已有的接口进行计算词与文档之间的相关性，可以参考进行关键词抽取。
