### ISSUE TITLE
wiki demo计算值和default_random_engine?

### ISSUE THREAD

**Issue by zhhaogen** [baidu/Familia#27]
无论在win10的Linux Bash还是ubuntu下编译,运行run_doc_distance_demo.sh
请输入文档1:
    在人工智能发展得最为系统化的硅谷，AI工程师们的薪水远高于其他领域的同行。随着人工智能概念的不断深入人心，人工智能的人才愈发的紧俏，时至今日，大学刚毕业的博士也能坐拥八九十万的年薪，与资深的硅谷工程师相媲美。
    请输入文档2:
    在国内，部分企业早已瞄准人才的短板，走在了业界的前面。百度是最早进行AI的人才培养布局的，他们同国内诸多高校开展合作，共建工程实验室，在数据开放和资源共享上进行各种合作。这种方式类似美国在人工智能教育领域推行的“硅谷-斯坦福”校企联动模式，一方面斯坦福大学为硅谷提供了人才和科研成果，另一方面硅谷为斯坦福大学提供资金支持和大数据，以助力他们的科研能有更大的突破。

得到的结果都是
Jensen-Shannon Divergence = 0.0533303
Hellinger Distance = 0.241383
与编写 demo的
    Jensen Shannon Divergence = 0.0283928
    Hellinger Distance = 0.179698
期望值不一样,(run_query_doc_sim_demo.sh也有出入)，是demo错了，还是我编译运行有问题？
default_random_engine 在visual studio查看下是mt19937,而linux表现来看是minstd_rand0，是不是将default_random_engine表示的更明确好点?

**Comment by lianrzh** [comment]
由于之前更新过模型，然后demo上对应的值没有更新，导致了你上面说的情况，现已修改，谢谢指出。另外，default_random_engine在不同编译器下的确会采用不同的generator，现在已指定为mt19937，在不同编译器下结果会保持一致，谢谢！
