### ISSUE TITLE
一直没有办法下载

### ISSUE THREAD

**Issue by XufengLi** [baidu/Familia#33]
第一步下载模型，`$ sh build.sh `，在linux上下载不成功

**Comment by lianrzh** [comment]
@XufengLi 可以给出更详细错误说明吗

**Comment by XufengLi** [comment]
@lianrzh 链接超时
`[xufeng@host-172-16-11-125 Familia-master]$ sh build.sh
rm -rf glog-0.3.4.tar.gz glog-0.3.4
wget --no-check-certificate http://raw.githubusercontent.com/ZeyuChen/third_party/master/package//glog-0.3.4.tar.gz  && tar -zxf glog-0.3.4.tar.gz
--2017-10-10 11:39:46--  http://raw.githubusercontent.com/ZeyuChen/third_party/master/package//glog-0.3.4.tar.gz
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.76.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.76.133|:80... fai                                                                                    led: Connection timed out.
Retrying.

--2017-10-10 11:41:55--  (try: 2)  http://raw.githubusercontent.com/ZeyuChen/third_party/mast                                                                                    er/package//glog-0.3.4.tar.gz
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.76.133|:80...
`

**Comment by lianrzh** [comment]
@XufengLi 这个应该是你机器网络的问题，我这边试了，可以正常下载

**Comment by XufengLi** [comment]
@lianrzh OK，那我再试一试

**Comment by XufengLi** [comment]
@lianrzh 确实是我的linux服务器的原因，服务器不能上网，请问有本地安装的版本或者方法吗？

**Comment by lianrzh** [comment]
@XufengLi 可以本地下载对应需要的package，然后再上传到服务器，对应去掉wget的命令即可

**Comment by XufengLi** [comment]
@lianrzh 安装包都弄好了，就是编译的最后一部生成familia.so文件时会报错，也没生成so文件，这是什么原因？
编译代码：
python/demo/familia.so: python/cpp/familia_wrapper.cpp familia 
$(CXX) $(INCPATH) $(CXXFLAGS) -c $< -o python/cpp/familia_wrapper.o $(CXX) $(INCPATH) $(CXXFLAGS) -shared python/cpp/familia_wrapper.o $(LDFLAGS_SO) -l$(PYTHON_VERSION) -o $@
报错信息：
`g++ -I./include/ -I./include/familia -I./third_party/include -I/usr/local/python3/include/python3.6m -pipe -W -Wall -fPIC -std=c++11 -fno-omit-frame-pointer -fpermissive -O3 -ffast-math -c python/cpp/familia_wrapper.cpp -o python/cpp/familia_wrapper.o
python/cpp/familia_wrapper.cpp:427:1: warning: missing initializer for member ‘PyModuleDef::m_slots’ [-Wmissing-field-initializers]
 };
 ^
python/cpp/familia_wrapper.cpp:427:1: warning: missing initializer for member ‘PyModuleDef::m_traverse’ [-Wmissing-field-initializers]
python/cpp/familia_wrapper.cpp:427:1: warning: missing initializer for member ‘PyModuleDef::m_clear’ [-Wmissing-field-initializers]
python/cpp/familia_wrapper.cpp:427:1: warning: missing initializer for member ‘PyModuleDef::m_free’ [-Wmissing-field-initializers]
g++ -I./include/ -I./include/familia -I./third_party/include -I/usr/local/python3/include/python3.6m -pipe -W -Wall -fPIC -std=c++11 -fno-omit-frame-pointer -fpermissive -O3 -ffast-math -shared python/cpp/familia_wrapper.o -L/data00/xufeng/Familia-master/third_party/lib -L/usr/local/python3/lib -L./build/ -lfamilia -lprotobuf -lglog -lgflags -lpython3.6m -o python/demo/familia.so
/usr/bin/ld: /usr/local/python3/lib/libpython3.6m.a(listobject.o): relocation R_X86_64_32 against `_Py_NoneStruct' can not be used when making a shared object; recompile with -fPIC
/usr/local/python3/lib/libpython3.6m.a: could not read symbols: Bad value
collect2: error: ld returned 1 exit status
make: *** [python/demo/familia.so] Error 1
`

**Comment by XufengLi** [comment]
@lianrzh 
![360 20171013110910226](https://user-images.githubusercontent.com/27847060/31528631-159d8a86-b007-11e7-8321-4af7f7dd2802.jpg)

**Comment by XufengLi** [comment]
@lianrzh 
![360 20171013111114112](https://user-images.githubusercontent.com/27847060/31528673-59d9944c-b007-11e7-962a-19eebc91fc48.jpg)

**Comment by lianrzh** [comment]
@XufengLi 这一部分是生成python库，根据错误提示应该链接你本地机器的libpython错误，需要你找到本地的路径，对应修改这句命令中的`-l$(PYTHON_VERSION)`

**Comment by XufengLi** [comment]
@lianrzh 我找了下路径是对的，错误中提示的是 could not read symbols:不能读取符号，不知道是什么原因

**Comment by XufengLi** [comment]
@lianrzh 你好，实在是自己解决不了，又来问您了。我在路径下放了libpython.a, 但是提示总是找不到这个库。
cc1plus: warning: /usr/local/python3/include/libpython3.6m.a: not a directory [enabled by default]
python/cpp/familia_wrapper.cpp:5:20: fatal error: Python.h: No such file or directory
 #include <Python.h>
                    ^
compilation terminated.
make: *** [python/demo/familia.so] Error 1

**Comment by lianrzh** [comment]
@XufengLi 通过上面的错误提示，是没有正确链接到你机器的libpython，建议你搜索一下你本地的libpython地址，然后链接上去，例如上面提到的`could not read symbols:不能读取符号`问题，这种大多跟编译器版本相关，这种错误可以通过搜索找到对应的解决方法。

**Comment by XufengLi** [comment]
问题已解决，贴上解决方法。  [在linux安装依赖于python包时，报错libpython.a: conld not read symbols - CSDN博客](http://blog.csdn.net/ilikede/article/details/78253602)
