### ISSUE TITLE
主题去重工具是否可以适用于twe模型？

### ISSUE THREAD

**Issue by brandyaptx** [baidu/Familia#34]
主题去重工具脚本是否可以适用于twe模型，还是说只能用于lda模型？

**Comment by lianrzh** [comment]
@brandyaptx 暂时不适用于twe模型，只对lda模型进行修改，近期我们再添加对TWE模型的支持

**Comment by lianrzh** [comment]
@brandyaptx 在`tools/TWE_tools`目录下提供了工具对TWE模型进行处理，主题向量位于模型最后面，可以将二进制模型转为文本，再根据具体情况（例如删减某些主题进行压缩）进行处理，再重新转为二进制。
