### ISSUE TITLE
Wiki中引用的外部链接URL出现拼写错误

### ISSUE THREAD

**Issue by howl-anderson** [baidu/Familia#36]
Wiki: [https://github.com/baidu/Familia/wiki/语义匹配应用介绍](https://github.com/baidu/Familia/wiki/%E8%AF%AD%E4%B9%89%E5%8C%B9%E9%85%8D%E5%BA%94%E7%94%A8%E4%BB%8B%E7%BB%8D) 中
>  对于较难的短文本-短文本语义匹配任务，则可以考虑引入有监督信号并利用 Deep Structured Semantic Model(DSSM)[5] 或 Convolutional Latent Semantic Model(CLSM)[9] 这些更复杂的神经网络模型进行语义相关性的计算。

`Convolutional Latent Semantic Model(CLSM)[9]` 的链接URL出现拼写错误：microsoft.com 被错误拼写成 microsoft.uom

**Comment by lianrzh** [comment]
@howl-anderson 感谢指出这个错误，已修正！
