### ISSUE TITLE
案例2: 文档关键词抽取没有提供python模块？

### ISSUE THREAD

**Issue by ajoeajoe** [baidu/Familia#37]
貌似没有提供关键词抽取的python接口，在使用过程中关键词抽取速度快吗，好像python API目前不算很友好

**Comment by lianrzh** [comment]
@ajoeajoe Demo提供的是使用的示例，没有针对速度进行特别优化，建议可以根据使用场景进行处理，python API是针对C++的接口进行包装，基本保持一致，可以具体说出哪些问题？

**Comment by ajoeajoe** [comment]
https://github.com/baidu/Familia/wiki/%E8%AF%AD%E4%B9%89%E5%8C%B9%E9%85%8D%E5%BA%94%E7%94%A8%E4%BB%8B%E7%BB%8D 这里有关键词抽取模块功能，但python demo里面并没提供相关demo，我想试用此功能，性能如何（是否能满足工业级别应用）

**Comment by lianrzh** [comment]
对应添加了python关键词demo,提供了LDA跟TWE两种计算方式，分别对应`document_keywords_demo.py`和`document_twe_keywords_demo.py`,对整个工具使用有什么建议欢迎提出，或者可以直接修改再合并进来。

**Comment by ajoeajoe** [comment]
https://github.com/baidu/Familia/wiki/%E8%AF%AD%E4%B9%89%E5%8C%B9%E9%85%8D%E5%BA%94%E7%94%A8%E4%BB%8B%E7%BB%8D 
我说的是上面的链接中的第二个应用案例—**“文档关键词抽取”**，并不是计算相似度，看了下你们的familia_wrapper.py接口，并没提供关键词抽取功能模块，可能我表述不太清晰，非常感谢你们的及时反馈。

**Comment by lianrzh** [comment]
关键词抽取是计算每个词与文档的相关性，然后再选取topk作为关键词，你可以根据上面几个接口的输出选取适当的个数即可！

**Comment by ajoeajoe** [comment]
恩。好的
