### ISSUE TITLE
运行sh build.sh 因缺失Python.h文件失败

### ISSUE THREAD

**Issue by shanshanhello** [baidu/Familia#40]
在Ubuntu操作系统下，下载安装包后，运行sh build.sh失败，因缺失python.h文件

**Comment by shanshanhello** [comment]
g++ -I./include/ -I./include/familia -I./third_party/include -I/usr/include/python3.5m -pipe -W -Wall -fPIC -std=c++11 -fno-omit-frame-pointer -fpermissive -O3 -ffast-math -c python/cpp/familia_wrapper.cpp -o python/cpp/familia_wrapper.o
python/cpp/familia_wrapper.cpp:5:20: fatal error: Python.h: 没有那个文件或目录
compilation terminated.
Makefile:106: recipe for target 'python/demo/familia.so' failed
make: *** [python/demo/familia.so] Error 1

**Comment by lianrzh** [comment]
@shanshanhello  这个是因为没找到你对应的Python.h文件，可以先找到你系统对应的python.h路径，然后添加到g++编译的指令上即可
