### ISSUE TITLE
运行sh build.sh 报错

### ISSUE THREAD

**Issue by danger119** [baidu/Familia#41]
build/vose_alias.o build/inference_engine.o build/model.o build/vocab.o build/document.o build/sampler.o build/config.o build/util.o build/semantic_matching.o build/tokenizer.o build/demo/inference_demo.o build/demo/doc_distance_demo.o build/demo/query_doc_sim_demo.o build/demo/word_distance_demo.o build/demo/topic_word_demo.o build/demo/document_keywords_demo.o build/demo/show_topic_demo.o
g++ -pipe -W -Wall -fPIC -std=c++11 -fno-omit-frame-pointer -fpermissive -O3 -ffast-math -I./include/ -I./include/familia -I./third_party/include -I/home/hadoop/anaconda2/include/python2.7 build/demo/inference_demo.o  -L/home/hadoop/lg/Familia/third_party/lib -L/home/hadoop/anaconda2/lib -L./build/ -lfamilia -lprotobuf -lglog -lgflags -o inference_demo
./build//libfamilia.a(model.o)：在函数‘familia::TopicModel::topic_sum(int) const’中：
model.cpp:(.text+0x22a)：对‘std::__throw_out_of_range_fmt(char const*, ...)’未定义的引用
./build//libfamilia.a(sampler.o)：在函数‘familia::MHSampler::construct_alias_table()’中：
sampler.cpp:(.text+0xabe)：对‘std::__throw_out_of_range_fmt(char const*, ...)’未定义的引用
./build//libfamilia.a(util.o)：在函数‘familia::split(std::vector<std::string, std::allocator<std::string> >&, std::string const&, char)’中：
util.cpp:(.text+0x1ec)：对‘std::__throw_out_of_range_fmt(char const*, ...)’未定义的引用
/home/hadoop/lg/Familia/third_party/lib/libprotobuf.a(common.o)：在函数‘std::vector<void (*)(), std::allocator<void (*)()> >::_M_range_check(unsigned long) const’中：
common.cc:(.text._ZNKSt6vectorIPFvvESaIS1_EE14_M_range_checkEm[_ZNKSt6vectorIPFvvESaIS1_EE14_M_range_checkEm]+0x4a)：对‘std::__throw_out_of_range_fmt(char const*, ...)’未定义的引用
collect2: 错误：ld 返回 1
make: *** [all] 错误 1

一直报错。请问是什么原因？

**Comment by lianrzh** [comment]
可以给出具体的信息，例如系统，编译器版本等

**Comment by danger119** [comment]
系统版本
Linux version 2.6.32-642.6.2.el6.x86_64 (mockbuild@worker1.bsys.centos.org) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-17) (GCC) )
编译器
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/local/libexec/gcc/x86_64-pc-linux-gnu/6.1.0/lto-wrapper
目标：x86_64-pc-linux-gnu
配置为：../configure --enable-checking=release --enable-languages=c,c++ --disable-multilib
线程模型：posix
gcc 版本 6.1.0 (GCC)

**Comment by LiangXD** [comment]
我想了解下，模型训练的数据在什么地方可以找到啊
