### ISSUE TITLE
Ubuntu16.04中libglog.so.0缺失

### ISSUE THREAD

**Issue by RingWong** [baidu/Familia#42]
在Ubuntu16.04中使用Familia，已在/etc/profile中添加export LD_LIBRARY_PATH=./third_party/lib:$LD_LIBRARY_PATH，并已source，但是在python2环境中运行python的demo时依旧报ImportError: libglog.so.0: cannot open shared object file: No such file or directory这个错误，请问该如何解决？谢谢！
另外，如何在python3中调用Familia？

**Comment by RingWong** [comment]
问题已解决，要添加绝对路径，而不是相对路径，大意了。

**Comment by adzhua** [comment]
@RingWong 你好我也遇到这个问题，这儿得决定路径是什么意思？
