### ISSUE TITLE
Python提取主题词

### ISSUE THREAD

**Issue by RingWong** [baidu/Familia#43]
请问Python有打算开放输入主题编号，输出主题词的接口吗？现只有nearest_words_around_topic这一个接口，但得到的结果没有直接获得主题词好。
另外，电商领域的模型什么时候开放呢？
谢谢！

**Comment by lianrzh** [comment]
@RingWong 每个模型下有对应的topic_words.txt文件，可以直接从该文件中获取主题词结果。
电商模型由于训练数据不足问题，一直效果不符合预期，需要更多数据方可再重新训练。

**Comment by jerrymomo10** [comment]
@lianrzh 请问这个工具有可以衡量Topic的指标吗？

**Comment by jerrymomo10** [comment]
@lianrzh 请问这个工具是不是只有infer的功能，没有训练的？

**Comment by lianrzh** [comment]
@jerrymomo10 恩，只提供了模型跟infer工具，可以通过查看主题下词的情况来衡量效果
