### ISSUE TITLE
Familia可以进行预测吗？

### ISSUE THREAD

**Issue by why1988seu** [baidu/Familia#44]
Familia可以和fasttext一样进行文本分类预测吗？如果可以，如何使用？

**Comment by lianrzh** [comment]
@why1988seu 是可以进行文本分类预测的，对文本进行推断得到主题分布之后，可以作为对应文本的特征加入到回归模型中进行推断，如若没有标注样本，则可以试验每个主题会一个类别，选取文本分布概率最高的主题作为其分类结果。
