### ISSUE TITLE
TWE_tools里的bin2txt怎么用？

### ISSUE THREAD

**Issue by yinjianhong** [baidu/Familia#49]
TWE_tools里的bin2txt怎么用？
能否把词向量转成文本格式？

**Comment by lianrzh** [comment]
用法`./bin2txt <FILE> <OUTPUT>`，由于在Linux进行编译，因此暂时不支持MAC，迟些会提供源码。

**Comment by hitwangshuai** [comment]
请问啥时候提供源代码，运行提示出错：ld-linux-x86-64.so.2: bad ELF interpreter: No such file or directory

**Comment by hitwangshuai** [comment]
同出错，运行提示出错：ld-linux-x86-64.so.2: bad ELF interpreter: No such file or directory
