### ISSUE TITLE
无法安装成功

### ISSUE THREAD

**Issue by zhang19** [baidu/Familia#51]
系统ubuntu 17,执行sh build.sh后报错如下：
python/cpp/familia_wrapper.cpp:517:1: warning: missing initializer for member ‘PyModuleDef::m_traverse’ [-Wmissing-field-initializers]
python/cpp/familia_wrapper.cpp:517:1: warning: missing initializer for member ‘PyModuleDef::m_clear’ [-Wmissing-field-initializers]
python/cpp/familia_wrapper.cpp:517:1: warning: missing initializer for member ‘PyModuleDef::m_free’ [-Wmissing-field-initializers]
g++ -I./include/ -I./include/familia -I./third_party/include -I/usr/include/python3.6 -pipe -W -Wall -fPIC -std=c++11 -fno-omit-frame-pointer -fpermissive -O3 -ffast-math -shared python/cpp/familia_wrapper.o -L/home/zyb/dev/Familia/Familia/third_party/lib -L/usr/lib -L./build/ -lfamilia -lprotobuf -lglog -lgflags -lpython3.6 -o python/demo/familia.so
/usr/bin/ld: 找不到 -lpython3.6
collect2: error: ld returned 1 exit status
Makefile:106: recipe for target 'python/demo/familia.so' failed
make: *** [python/demo/familia.so] Error 1

请教下怎么解决？谢谢

**Comment by lianrzh** [comment]
@zhang19 python路径没设置正确，需要根据你本地的python路径进行重新指定。
