### ISSUE TITLE
不支持python3

### ISSUE THREAD

**Issue by teaGod-s** [baidu/Familia#52]
系统环境python2和python3共存，执行build.sh后生成的familia.so可以用在python2中，但是不能用在python3中
```
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import familia
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dynamic module does not define module export function (PyInit_familia)
```

**Comment by teaGod-s** [comment]
已解决

**Comment by Goooaaal** [comment]
请问如何 使用python接口  我的代码无法导入familia
import familia
ImportError Traceback (most recent call last)
in ()
----> 1 import familia

ImportError: libglog.so.0: cannot open shared object file: No such file or directory

我已经在/etc/profile 里加入此变量：
export LD_LIBRARY_PATH=/home/tiger/Destop/Familia/third_party/lib:$LD_LIBRARY_PATH
仍然无效。

**Comment by Leaking** [comment]
你好，请问是怎么解决的呢？
我最开始使用Python2的环境，按照文档安装，运行demo（C++版本和Python版本两份demo），都正常
后来尝试用python3运行demo，发现了和你一样的问题

**Comment by teaGod-s** [comment]
我的环境已经没了，具体的步骤忘了，记得他的编译脚本里面有代码是获取系统的python命令，然后找到python命令所在的位置，之后都是用的这个位置的python。你要把这个python改成python3，这样获取的就是python3的位置。
或者你也可以把自己系统的python3改别名为python

**Comment by Leaking** [comment]
谢谢！

teaGod <notifications@github.com> 于 2018年8月28日周二 下午6:00写道：

**Comment by sladesha** [comment]
Makefile指定Python3的PYTHON_PATH、PYTHON_VERSION、PYTHON_INCLUDE即可
