### ISSUE TITLE
demo 问题

### ISSUE THREAD

**Issue by machaelliu** [baidu/Familia#53]
./inference_demo --model_dir="./model/news" --conf_file="lda.conf"               
ERROR: unknown command line flag 'conf_file'
ERROR: unknown command line flag 'model_dir'

请问这是什么原因？

**Comment by machaelliu** [comment]
还有这个：
./run_topic_word_demo.sh 
ERROR: unknown command line flag 'emb_file'
ERROR: unknown command line flag 'model_dir'
ERROR: unknown command line flag 'topic_words_file'

**Comment by caiyinqiong** [comment]
你好，我也在尝试用这个，是否可以交流一下，希望看到之后可以和我联系一下，我的邮箱：1198593462@qq.com。谢谢~

**Comment by lianrzh** [comment]
@machaelliu 看起来是gflag没有安装正确，你检查一下。
