### ISSUE TITLE
运行build.sh出错

### ISSUE THREAD

**Issue by xlx0010** [baidu/Familia#55]
windows10下用cygwin运行build.sh, 出现错误如图。
请问这是为什么，怎么解决啊？谢谢！！
![_20180412002619](https://user-images.githubusercontent.com/31838190/38629965-2ade5bae-3de8-11e8-805f-2fd8eebc7e0c.png)

**Comment by lianrzh** [comment]
@xlx0010 现在代码还没支持windows，上面的提示是glog的错误，建议换个linux或者Mac的系统使用。

**Comment by xlx0010** [comment]
哦好的，谢谢！
