### ISSUE TITLE
Model的格式是开放的吗？

### ISSUE THREAD

**Issue by conghuawang** [baidu/Familia#59]
你好，
   试用了一下familia，觉得Project中提供的model效果不错。
   由于目前familia还未开放训练model的功能。
   所以，是否有计划开放model的格式呢？以便开发者自行训练专有模型。

**Comment by lianrzh** [comment]
你好，model的格式是开放的，每一行的格式为：第一列为词ID，之后每一列为主题ID：次数（词ID出现改主题ID下的次数）。
