### ISSUE TITLE
请教一下对query_doc_sim的理解

### ISSUE THREAD

**Issue by caiyinqiong** [baidu/Familia#60]
以下是我的理解，但不确定对不对，并有一些疑问，所以请教一下，盼回，感谢。
1. 输入query和document后，会使用LDA算法对document进行主题推断，即得到主题id和主题的概率。
2. 遍历query中的所有单词，根据TWE算法训练好的词向量表示和主题向量表示，计算cos相似度，使用相应的公式计算即可得到query和document的最终相似度。（公式贴不上，那个公式我知道，所以应该没有问题）
我的疑问如下：
1. 使用LDA算法对document进行主题推断是使用的http://www.jmlr.org/papers/volume3/blei03a/blei03a.pdf这篇论文的算法思想吗？
2. 我看之前别人提到的问题得知你们使用的是TWE-1模型。TWE-1是先训练得到词向量表示和主题向量表示，然后再结合形成主题词向量表示。。所以上述第2步中，计算cos相似度的词向量和主题向量仅是TWE-1训练好的词向量表示和主题向量表示吗？是不是此处和所谓的主题词向量无关？？根据源代码来看，query中的词是唯一确定的一个向量表示，而不是在不同的主题下有不同的表示（因为query过短，没有丰富的上下文信息来做主题推断）。
3. 虽然我看了TWE那篇论文，但对于训练过程仍然不太清晰。。是不是使用skip-gram模型先训练得到词向量表示，然后使用属于某个主题的词向量的平均值初始化主题向量，然后在词向量表示不变的情况下学习主题向量表示。那也就是说TWE-1模型训练得到的词向量表示和skip-gram训练得到的是一样的？？TWE-1的创新点是在于也学习了主题向量表示，并且可以进一步得到主题词嵌入？

**Comment by lianrzh** [comment]
@caiyinqiong 你好，第2步中，计算cos相似度的词向量和主题向量是用了TWE-1训练好的词向量表示和主题向量表示，这里的主题向量指的是主题词向量，而不是第一步得到的主题分布，第一步得到的主题概率在公式中会使用到。另外，第5点你的理解是跟我一致的。

**Comment by caiyinqiong** [comment]
好的 我理解了 非常感谢
