### ISSUE TITLE
如何使用自定义词表的功能导入主题模型中的词表

### ISSUE THREAD

**Issue by lujiaying** [baidu/Familia#63]
> 代码中内置简易的FMM分词工具，只针对主题模型中出现的词表进行正向匹配。若对分词和语义准确度有更高要求，建议使用商用分词工具，并使用自定义词表的功能导入主题模型中的词表。

请问如何使用自定义词表的功能导入主题模型中的词表呢？难道是直接修改 vocab.txt 文件吗？

**Comment by lianrzh** [comment]
@lujiaying 你理解错意思了，是建议使用商用分词工具，然后将`vocab.txt`导入到商用分词工具中，对`vocab.txt`进行修改是起不到作用的。

**Comment by lujiaying** [comment]
嗯嗯 我试了商用分词，假设我分词出了一个 out of vocab的词，做一些如短文本-长文本相似性计算，结果是0？

**Comment by lianrzh** [comment]
@lujiaying OOV的词是解决不了的，仅能支持原先词表中包含的词

**Comment by lujiaying** [comment]
OK 理解了
