### ISSUE TITLE
model 下载失败

### ISSUE THREAD

**Issue by Ringares** [baidu/Familia#64]
请问现在怎么下载模型

> --2018-08-01 14:55:41--  http://familia.bj.bcebos.com/models/news.v1.tar.gz
正在解析主机 familia.bj.bcebos.com (familia.bj.bcebos.com)... 202.106.5.21
正在连接 familia.bj.bcebos.com (familia.bj.bcebos.com)|202.106.5.21|:80... 已连接。
已发出 HTTP 请求，正在等待回应... 403 Forbidden
2018-08-01 14:55:41 错误 403：Forbidden。
tar: Error opening archive: Failed to open 'news.v1.tar.gz'

>--2018-08-01 14:55:41--  http://familia.bj.bcebos.com/models/webpage.tar.gz
正在解析主机 familia.bj.bcebos.com (familia.bj.bcebos.com)... 202.106.5.21
正在连接 familia.bj.bcebos.com (familia.bj.bcebos.com)|202.106.5.21|:80... 已连接。
已发出 HTTP 请求，正在等待回应... 403 Forbidden
2018-08-01 14:55:41 错误 403：Forbidden。
tar: Error opening archive: Failed to open 'webpage.tar.gz'

>--2018-08-01 14:55:41--  http://familia.bj.bcebos.com/models/novel.tar.gz
正在解析主机 familia.bj.bcebos.com (familia.bj.bcebos.com)... 202.106.5.21
正在连接 familia.bj.bcebos.com (familia.bj.bcebos.com)|202.106.5.21|:80... 已连接。
已发出 HTTP 请求，正在等待回应... 403 Forbidden
2018-08-01 14:55:41 错误 403：Forbidden。
tar: Error opening archive: Failed to open 'novel.tar.gz'

>--2018-08-01 14:55:41--  http://familia.bj.bcebos.com/models/weibo.tar.gz
正在解析主机 familia.bj.bcebos.com (familia.bj.bcebos.com)... 202.106.5.21
正在连接 familia.bj.bcebos.com (familia.bj.bcebos.com)|202.106.5.21|:80... 已连接。
已发出 HTTP 请求，正在等待回应... 403 Forbidden
2018-08-01 14:55:41 错误 403：Forbidden。
tar: Error opening archive: Failed to open 'weibo.tar.gz'

**Comment by lianrzh** [comment]
@Ringares 已经解决问题了，可以再试试下载，如果还不行的话，稍微再试试

**Comment by kongshanxuelin** [comment]
有无法下载了

**Comment by kongshanxuelin** [comment]
{"code":"AccountOverdue","message":"Your request is denied because there is an overdue bill of your account.","requestId":"1e37ac6b-7d5b-462b-ad8c-4d6d7b63c8ee"}
