### ISSUE TITLE
请问提供训练自己模型的接口吗

### ISSUE THREAD

**Issue by yuquanle** [baidu/Familia#7]

**Comment by ZeyuChen** [comment]
目前下一步计划是开放更多不同领域的模型并提供python版本的接口。训练部分目前还没有明确的计划。

**Comment by dogegg250** [comment]
如果没有训练代码，切词都不一能保持一致呀

**Comment by ZeyuChen** [comment]
由于我们模型的词表有开放，可以尝试使用外部分词的自定义词表功能导入模型的词表。只需要让分词能捕捉到相应的单词即可得到主题信息。
