### ISSUE TITLE
English readme

### ISSUE THREAD

**Issue by impredicative** [baidu/Familia#70]
The English readme doesn't look to be too well maintained. Please sync it with the default readme.

For example, it refers to the 2017 Arxiv paper. Please consider updating the reference to the currenr 2018 paper instead which I believe is https://arxiv.org/abs/1808.03733 . Thanks.

**Comment by impredicative** [comment]
It still links to the wrong paper. Is anyone competent working on this project, or is it a fraud?

**Comment by lianrzh** [comment]
@impredicative The paper is right now.

**Comment by impredicative** [comment]
Huh? It links to the 2017 paper, not the 2018 paper.

**Comment by lianrzh** [comment]
@impredicative Thank you. I just revised it.
