### ISSUE TITLE
好像simnet也做语义匹配，和Familia是什么关系呢？

### ISSUE THREAD

**Issue by yitian134** [baidu/Familia#73]
rt，看起来两者都可以做语义匹配？在实际应用时区别和分工是什么？

**Comment by lianrzh** [comment]
@yitian134 讲一下个人的理解，simnet是基于embedding的方式，会更适用短文本语义匹配场景，而Familia是基于对文档进行建模，会更适合长文本的场景。在实际中应用的话可以结合这两种，例如作为两个特征跟应用中其余特征再共同进行学习。

**Comment by yitian134** [comment]
@lianrzh 奥，是否可以这样理解呢？
simnet 是网络模型匹配，Familia 是主题模型匹配。实际使用的时候把这两个召回结果作为 rerank 的两个特征？常说的多模型排序是这个意思吗？
