### ISSUE TITLE
cannot find -l3.6.8

### ISSUE THREAD

**Issue by yangjinjie** [baidu/Familia#78]
您好，编译的时候出现如下报错，应该怎么解决？
g++ -I./include/ -I./include/familia -I./third_party/include -I/usr/local/include/python3.6m -pipe -W -Wall -fPIC -std=c++11 -fno-omit-frame-pointer -fpermissive -O3 -ffast-math -shared python/cpp/familia_wrapper.o -L/Familia-1.1.2/third_party/lib -L/usr/local/lib -L./build/ -lfamilia -lprotobuf -lglog -lgflags -l3.6.8 -o python/demo/familia.so
/usr/lib/gcc/x86_64-alpine-linux-musl/6.4.0/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find -l3.6.8
collect2: error: ld returned 1 exit status
make: *** [Makefile:104: python/demo/familia.so] Error 1

**Comment by lianrzh** [comment]
@yangjinjie 你机器对应的python依赖问题，可以找一下真实的python路径

**Comment by deepsmallsea033** [comment]
您好，微博主题模型下载完成后没有对应的twe文件，造成在跑run_topic_word_demo时加载emb文件信息错误

**Comment by lianrzh** [comment]
@deepsmallsea033 由于微博句子比较短，因为只公开了Sentence LDA模型，没有对应的twe文件，如果需要跑run_topic_word_demo，建议使用其他模型文件试试。

**Comment by deepsmallsea033** [comment]
好的，感谢

**Comment by deepsmallsea033** [comment]
@lianrzh  好的感谢
