### ISSUE TITLE
./inference_demo: not found?

### ISSUE THREAD

**Issue by lydemo** [baidu/Familia#8]
请问在执行sh run_inference_demo.sh后下载完model出现上述提示是什么原因？

**Comment by lianrzh** [comment]
出现这个问题是找不到可执行程序inference_demo，你需要先成功运行**sh build.sh**，才可以运行这些demo脚本

**Comment by lydemo** [comment]
sh build.sh也不能执行……提示make不存在

**Comment by lydemo** [comment]
这是为什么？

**Comment by lianrzh** [comment]
应该是你的系统没有安装make，你可以搜一下你的系统对应如何安装make，然后再运行build.sh就可以了
