### ISSUE TITLE
Fitting your own model

### ISSUE THREAD

**Issue by schatimo** [baidu/Familia#81]
Hi,

I highly appreciate that you offer this toolbox! 
I was wondering whether I can fit a model, e.g. a sentence-LDA, to my dataset instead of using one of the pre-trained models that you offer for model inference. In case this has already been asked by someone else earlier in Chinese, I am sorry...

Many thanks in advance!

**Comment by lianrzh** [comment]
@schatimo hi, you can change the format of your pre-trained model to be consistent with the familia model. The dictionary(`vocab_info.txt`) has 5 columns, among which the latter three are word id, word frequency and document frequency.

**Comment by lianrzh** [comment]
@schatimo Sorry, there is no open training module.
