### ISSUE TITLE
python下运行，报Fatal Python error: PyThreadState_Get: no current thread

### ISSUE THREAD

**Issue by Haozhuai** [baidu/Familia#83]

**Comment by lianrzh** [comment]
@Haozhuai 给一下详细的报错信息，以及你的环境配置

**Comment by orctom** [comment]
同错误，mac

**Comment by lianrzh** [comment]
@orctom 可能的原因是编译使用的python版本跟运行的python版本不一致导致的

**Comment by Haozhuai** [comment]
mac下报的错误，运行的python版本是anaconda下的python3.6。我网上查了很多论坛上也都是说编译使用的python版本跟运行的python版本不一致导致的
目前我用macport查看我的python环境sudo port select --list python
Warning: Unable to get active selected version: The specified group 'python' does not exist.
显示并不存在，而且homebrew下系统默认的python2.7已经被我删除了。
所以我在想如何查看或者指定编译使用的python版本呢？

**Comment by lianrzh** [comment]
@Haozhuai 可以参考Makefile里面定义的PYTHON_PATH进行查看。

**Comment by Haozhuai** [comment]
@lianrzh  您好，我makefile下python环境如下：

ifndef PYTHON_PATH
PYTHON_PATH = $(shell python -c"import sys; print(sys.prefix)")
endif

我在shell下运行python后结果如下
>>> import sys
>>> print(sys.prefix)
/anaconda3

这意思就是说我编译使用的是anaconda3吗？
我当前项目的interpreter是：/anaconda3/python.app/Contentes/MacOS/python?
请问这该怎么解决

**Comment by lianrzh** [comment]
@Haozhuai 你可以对应修改python路径，只要两个统一起来即可。

**Comment by orctom** [comment]
python3：不work
python2：work
都是conda的环境
要用python3啊，亲们～
ideas？？

**Comment by orctom** [comment]
由于python2和python3在C extension部分的写法不一样，所以如果编译时用的时python2，调用的时候用的时python3，就会找不到module，错误类似于`dynamic module does not define module export function`

```
  1 #if PY_MAJOR_VERSION >= 3
  2 static struct PyModuleDef moduledef = {
  3     PyModuleDef_HEAD_INIT,
  4     "familia",
  5     NULL,
  6     -1,
  7     Methods
  8 };
  9
 10 PyMODINIT_FUNC PyInit_familia(void) {
 11     return PyModule_Create(&moduledef);
 12 }
 13 #else
 14
 15 // 模块初始化
 16 PyMODINIT_FUNC initfamilia(void)
 17 {
 18     Py_InitModule("familia", Methods);
 19 }
 20 #32 
```

而python小版本之间应该是兼容的吧。
如果这个问题真的是网上所说的**由于编译版本和运行版本不一致**导致的，那究竟是哪里不一致导致的。。。

**Comment by orctom** [comment]
问题出在conda
原生python3：work
conda下>=3.6.2的都不work
3.6.1：work
