### ISSUE TITLE
http / REST API interface?

### ISSUE THREAD

**Issue by KrishnaPG** [baidu/Familia#84]
This looks great work - but all the demos seem to implying that this need to be run from command-line, which is not really industry grade.

Is there a way to consume this as service / http / REST api?

**Comment by lianrzh** [comment]
We haven't provided this function yet, so we suggest you use flark to build it.

**Comment by orctom** [comment]
Docker
```
docker run -d \
    --name familia \
    -e MODEL_NAME=news \
    -p 5000:5000 \
    orctom/familia
```
MODEL_NAME can be one of `news`/`novel`/`webpage`/`webo`

API
```http://localhost:5000/swagger/```
